src/TodoList.Web/Models/TodoListItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TodoList.Web.Models
{
    public class TodoListItemViewModel
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        public DateTime LastModifiedDate { get; set; }
    }

    public class TodoListItemUpdateViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

src/TodoList.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TodoList.Bussiness.Interface.Service;
using TodoList.Entity.Data;
using TodoList.Entity.Interface;

namespace TodoList.Web.Controllers
{
    public class HomeController : Controller
    {
       

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Technologies";

            return View();
        }
    }
}

src/TodoList.Web/Controllers/TodoListItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TodoList.Bussiness.DTO;
using TodoList.Bussiness.Interface.Service;
using TodoList.Web.Models;

namespace TodoList.Web.Controllers
{
    public class TodoListItemController : Controller
    {

        private ITodoListItemService _todoListItemService;

        public TodoListItemController(ITodoListItemService TodoListItemService)
        {
            _todoListItemService = TodoListItemService;
        }
        // GET: TodoListItem
        public JsonResult GetAll()
        {
            var TodoListItems = _todoListItemService.GetAll();
            var Result = TodoListItems.OrderByDescending(d=>d.Order)
                                      .Select(d => new TodoListItemViewModel {
                                            Id=d.Id,
                                            Name=d.Name,
                                            LastModifiedDate=d.LastModifiedDate
                                        });

            return Json(new 
            {
                count= Result.Count(),
                data = Result
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(TodoListItemViewModel Instance)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    IsSuccess = ModelState.IsValid,
                    ErrorMessage = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors))
                }, JsonRequestBehavior.DenyGet);
            }

            var TodoListItem = new TodoListItemDTO {
                Name = Instance.Name
            };
            var CreateResult = _todoListItemService.Create(TodoListItem);
            if (!CreateResult.IsSuccess) {
                return Json(new
                {
                    IsSuccess= CreateResult.IsSuccess,
                    ErrorMessage = CreateResult.Message
                }, JsonRequestBehavior.DenyGet);
            }
            return Json(new
            {
                IsSuccess = CreateResult.IsSuccess,
                Data= CreateResult.ResultItems.FirstOrDefault()
            }, JsonRequestBehavior.DenyGet);

        }

        [HttpPost]
        public JsonResult Update(TodoListItemUpdateViewModel Instance)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    IsSuccess = ModelState.IsValid,
                    ErrorMessage = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors))
                }, JsonRequestBehavior.DenyGet);
            }

            var TodoListItem = new TodoListItemDTO
            {
                Id= Instance.Id,
                Name = Instance.Name
            };
            var UpdateResult = _todoListItemService.Update(TodoListItem);
            if (!UpdateResult.IsSuccess)
            {
                return Json(new
                {
                    IsSuccess = UpdateResult.IsSuccess,
                    ErrorMessage = UpdateResult.Message
                }, JsonRequestBehavior.DenyGet);
            }

            return Json(new
            {
                IsSuccess = UpdateResult.IsSuccess,
                Data = UpdateResult.ResultItems.FirstOrDefault()
            }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult Delete(Guid Id)
        {

            if (Id==Guid.Empty) {
                return Json(new
                {
                    IsSuccess =false,
                    ErrorMessage ="Request Parameters error" 
                }, JsonRequestBehavior.DenyGet);
            }

            var DeleteResult = _todoListItemService.Delete(Id);
            if (!DeleteResult.IsSuccess)
            {
                return Json(new
                {
                    IsSuccess = DeleteResult.IsSuccess,
                    ErrorMessage = DeleteResult.Message
                }, JsonRequestBehavior.DenyGet);
            }

            return Json(new
            {
                IsSuccess = DeleteResult.IsSuccess,
                Data = DeleteResult.ResultItems.FirstOrDefault()
            }, JsonRequestBehavior.DenyGet);
        }


    }
}

src/TodoList.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Message</h2>

<div class="row">
    <div class="col-md-12">
        <ul class="list-group customlist" id="technologyList">
            <li class="list-group-item list-item">
                <p>ASP.NET MVC5</p>
            </li>
            <li class="list-group-item list-item">
                <p>
                    Entity Framework 6
                </p>
            </li>
            <li class="list-group-item list-item">
                <p>
                    Autofac
                </p>
            </li>
            <li class="list-group-item list-item">
                <p>
                    SQL Server Express LocalDB
                </p>
            </li>
            <li class="list-group-item list-item">
                <p>JQuery</p>
            </li>
            <li class="list-group-item list-item">
                <p>Bootstrap 3</p>
            </li>
        </ul>
    </div>
</div>

src/TodoList.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section styles{
    <style>
        .jumbotron {
            margin-bottom: 10px;
        }
        .content-row {
             overflow-y: auto;
            max-height: calc(100vh - 450px);
            min-height:200px;
        }

        footer {
          text-align: center;
        }

        .list-item {
          display: flex;
        }
        .list-item p {
            flex: 7 0;
            word-wrap: break-word;
            min-width: 0;
            margin: 5px auto;
        }
        .list-item .list-item-cmdgroup{
            flex: 1 0;
            justify-content:center;
            display: flex;
        }

        .list-item-cmd {
          margin-bottom:10px;
        }

        .alert-anchor {
            position: fixed;
            right: 0;
            left: 0;
            border-width: 0 0 1px;
            z-index:1042;
        }
       
         .modal {
            overflow-y:unset;
        }
        .modal-dialog {
            margin: 200px auto;
        }
        body.modal-open, .modal-open .navbar-fixed-top, .modal-open .navbar-fixed-bottom {
             margin: 0;
        }
    </style>
}

<div id="alertarea" class="alert-anchor"></div>

<div class="jumbotron">
    <h1>TodoList</h1>
    <p class="lead">todo list app with CRUD features</p>
</div>

<div class="row">
    <div class="col-md-2 col-md-offset-10">
        <button type="button" class="btn btn-primary btn-lg btn-block list-item-cmd list-item-add" data-toggle="modal" data-target="#createModal">Create</button>
    </div>
</div>

<div class="row content-row">
    <div class="col-md-12">
        <ul class="list-group customlist" id="todolist">

        </ul>
    </div>
</div>


<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="createModalLongTitle">新建</h5>
            </div>
            <div class="modal-body">
                <form id="create-todolistItem-form">
                    <div class="form-group">
                        <label for="create-todolistitem-name" class="control-label">名稱</label>
                        <input type="text" class="form-control" id="create-todolistitem-name" placeholder="請輸入名稱...">
                    </div>
                </form>              
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="saveTodoListItemBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="editModalLongTitle">編輯</h5>
            </div>
            <div class="modal-body">
                <form id="edit-todolistItem-form">
                    <div class="form-group" style="display:none">
                        <label for="edit-todolistitem-id" class="control-label">Id</label>
                        <input type="text" class="form-control" id="edit-todolistitem-id" readonly>
                    </div>
                    <div class="form-group">
                        <label for="edit-todolistitem-name" class="control-label">名稱</label>
                        <input type="text" class="form-control" id="edit-todolistitem-name" placeholder="請輸入名稱...">
                    </div>
                </form>   
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="updateTodoListItemBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    
    <script>
        //namespace
        var todolist = {
            id: "todolist",
            url: {
                read: "@Url.Action("GetAll","TodoListItem")",
                save: "@Url.Action("Create", "TodoListItem")",
                update: "@Url.Action("Update", "TodoListItem")",
                destroy: "@Url.Action("Delete", "TodoListItem")"
            },
            alertTypeList:["success", "info", "warning", "danger"]
        };

        function initTodoListItems(){
            emptyListItems();
            getTodoListItems();
        }

        //ajax-callback
        function getTodoListItems() {
            $.ajax({
                url: todolist.url.read,
                success: function (result) {
                    createListItems(todolist.id, result.data);
                }
            });
        }

        function saveListItem(todoListItem) {
            var params = Object.assign({}, todoListItem);
            $.ajax({
                method: "Post",
                data: params,
                url: todolist.url.save,
                success: function (result) {
                    if (result.IsSuccess)
                    {
                        createListItems(todolist.id, [result.Data]);
                        showAlert("success", "create success!");

                        //modal behavior
                        $('#createModal').modal('hide');
                        var $form = $("#create-todolistItem-form");
                        if ($form.length !== 0)
                        {
                            $form[0].reset();
                        }
                    }
                    else
                    {
                        showAlert("danger", "create fail!");
                    }
                }
            });
        }


        function updateListItem(todoListItem) {
            var params = Object.assign({}, todoListItem);
            $.ajax({
                method: "Post",
                data: params,
                url: todolist.url.update,
                success: function (result) {
                    if (result.IsSuccess) {
                      
                        showAlert("success", "update success!");
                        editListItem(todoListItem);
                        //modal behavior
                        $('#editModal').modal('hide');
                    }
                    else {
                        showAlert("danger", "update fail!");
                    }
                }
            });
        }

        function deleteListItem(todoListItem) {
            var params = Object.assign({}, todoListItem);
            $.ajax({
                method: "Post",
                data: params,
                url: todolist.url.destroy,
                success: function (result) {
                    if (result.IsSuccess) {
                        deleteListItems([todoListItem]);
                        showAlert("success", "delete success!");
                    }
                    else {
                        showAlert("danger", "delete fail!");
                    }
                }
            });
        }

        //client-side
        function createListItems(listId,data) {
            var listItemsHtml= data.map(function(i){
                var itemHtml = '<li id="' + i.Id + '" class="list-group-item list-item">'+
                                    '<p>' + i.Name + '</p>'+
                                    '<div class="list-item-cmdgroup">'+
                                            '<span class="btn btn-light glyphicon glyphicon-pencil list-item-edit" data-toggle="modal" data-target="#editModal"></span>' +
                                            '<span class="btn btn-light glyphicon glyphicon-remove list-item-remove"></span>' +
                                    '</div>'+
                                '</li>';
                return itemHtml;
            });
            $("#" + listId).prepend(listItemsHtml);
        }

        function deleteListItems(data) {
            data.forEach(function (i) {
                $("#" + i.Id).remove()
            });
        }

        function emptyListItems(listId) {
            $("#"+listId).empty("");
        }

        function editListItem(listItem) {
            var $nameElement = $("#" + listItem.Id).children("p");
            $nameElement.html(listItem.Name);
        }

        //alert
        function showAlert(type, msg) {
            var typelist = todolist.alertTypeList;
            var typeIndex = typelist.indexOf(type);
            if (typeIndex < 0) {
                return;
            }

            var alertType = 'alert-' + typelist[typeIndex];
            var alertHtml = '<div class="alert alert-dismissible ' + alertType + '" role="alert">' +
                                '<p>'+msg+ '</p>'
                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
                                '<strong>Warning!</strong> Better check yourself, you\'re not looking too good.' +
                            '</div>';
             $("#alertarea").html(alertHtml);

             setTimeout(hideAlert, 3000);
        }

        function hideAlert() {
            $(".alert").alert('close');
        }

        $(document).ready(function () {
            initTodoListItems();

            $("#saveTodoListItemBtn").on("click", function () {
                var todoListItemName = $("#create-todolistitem-name").val();
                if (todoListItemName==="") {

                    showAlert("warning", "please type todolist item's name");
                    return;
                }
                var params = {
                    Name: todoListItemName
                };

                saveListItem(params);

            });

            $("#todolist").on("click", ".list-item-remove", function (e) {
                var isDeleteConfirm = confirm("Are you sure you want to delete this item?");
                if (!isDeleteConfirm)
                {
                    return;
                }
                var $todoListItemElement = $(e.target).parents(".list-item");
                if ($todoListItemElement.length===0) {
                    return;            
                }

                ////front end validation
                var params = {
                    Id:$todoListItemElement[0].id,
                };
         
                deleteListItem(params);

            });

            $('#editModal').on('show.bs.modal', function (event) {

                var $button = $(event.relatedTarget)
                var $todoListItemElement = $button.parents(".list-item");
                if ($todoListItemElement.length === 0) {
                    return;
                }
                var id = $todoListItemElement[0].id;
                var name = $todoListItemElement.find("p");
                $("#edit-todolistitem-name").val(name.text());
                $("#edit-todolistitem-id").val(id);

                
            });

            $("#updateTodoListItemBtn").on("click", function () {
                var todoListItemName = $("#edit-todolistitem-name").val();
                if (todoListItemName === "") {

                    showAlert("warning", "please type todolist item's name");
                    return;
                }

                var params = {
                    Id:  $("#edit-todolistitem-id").val(),
                    Name: todoListItemName
                };

                updateListItem(params);
            });

            $('form').submit(false);
        });
    </script>
        
}

src/TodoList.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TodoList</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TodoList", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TodoList</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>